### PR TITLE
Remove enable_cs due to unsoundness

### PR DESCRIPTION
**Pull request by YuhanLiin**
Breaking change. See rust-embedded/bare-metal#42 for discussion.

### CODE REVIEW

**Comment by cr1901** [comment]
For completeness' sake, do you mind adding a CHANGELOG.md `Removed` entry and bumping the version number to `0.3.0`?

**Comment by YuhanLiin** [comment]
Actually maybe we can change `enable_cs` to unsafe. This would prevent the misuse where the `CriticalSection` is used after enabling interrupts. The drawback is that we now have two unsafe APIs for enabling interrupts. What do you think?

**Comment by cr1901** [comment]
@YuhanLiin Making it `unsafe` is a visible API change, and thus a breaking change. And passing in a `CriticalSection` is not actually doing anything useful in light of the fact that a user can `clone` a `CriticalSection` token.

I would rather get rid of `enable_cs` completely, and update the docs for `enable` from:

```
/// - Do not call this function inside an `interrupt::free` critical section
```

to something like:

```
/// - In any function `f()` that calls `enable`, `CriticalSection` or `&CriticalSection` tokens cannot be used in `f()`'s body after the 
///   call to `enable`. If `f()` owns `CriticalSection` tokens, it is recommended to [`drop`](https://doc.rust-lang.org/nightly/core/mem/fn.drop.html)
///   these tokens before calling `enable`.
```

We can think of another way to make fully safe MSP430 applications over time, perhaps refining an `init` attribute. _I'm_ personally not losing much sleep over a bit of `unsafe`, though it is a shame this didn't work out. At least passing in a `CriticalSection` is still a valid optimization :D!

**Comment by YuhanLiin** [comment]
> At least passing in a CriticalSection is still a valid optimization :D!
>
I remember the proc macro for that change being a pain to implement, so it's good that it doesn't need to be reverted.

**Review by cr1901 — APPROVED** [review]

**Pull request merged**
